### PR TITLE
validators: png signature as bytes

### PR DESCRIPTION
**Pull request by moyogo**

### CODE REVIEW

**Comment by adrientetar** [comment]
There's an assertion at the beginning of this function which isn't written as a function. Does that work with Python3?

**Comment by moyogo** [comment]
`assert` is still a statement in Python 3. https://docs.python.org/3/reference/simple_stmts.html?highlight=assert#the-assert-statement

**Comment by adrientetar** [comment]
Okay, my bad;

**Comment by moyogo** [comment]
Thanks!

**Pull request merged**
